#!/bin/bash
set -x
SOURCE_DIR=/var/lib/tsuru
${SOURCE_DIR}/base/deploy $@

source ${SOURCE_DIR}/config

cd $CURRENT_DIR
# $2 == git-ref-id
git archive --format=tar $2 | sudo /bin/sh -c "rm -rf /app && mkdir /app && tar xvf - -C /app"

sudo /build/builder
# fix the perms
sudo chown -R ubuntu:ubuntu /app /home/application/current
sudo chmod +x /var/lib/tsuru/start

# tell heroku app what port to listen on
export HOME=/app
export PORT=8888

if [ -d $HOME/.profile.d/ ]; then
  for file in $HOME/.profile.d/*; do
    source $file;
  done
fi

python ${SOURCE_DIR}/hooks.py
