#!/bin/bash
set -x
SOURCE_DIR=/var/lib/tsuru
${SOURCE_DIR}/base/deploy $@

source ${SOURCE_DIR}/config

cd $CURRENT_DIR
# $2 == git-ref-id
git archive --format=tar $2 | sudo /bin/sh -c "rm -rf /app && mkdir /app && tar xvf - -C /app"
sudo /build/builder
# fix the perms
sudo chown -R ubuntu:ubuntu /app
sudo cat > /var/lib/tsuru/start <<EOF
#!/bin/bash -l

source /var/lib/tsuru/config
export HOME=/app
for file in \$HOME/.profile.d/*; do source \$file; done
hash -r
sudo -E /usr/local/bin/circusd /etc/circus/circus.ini --daemon --log-output /var/log/circus.log

EOF
chmod +x /var/lib/tsuru/start

# tell heroku app what port to listen on
export HOME=/app
export PORT=8888

# load profile

for file in $HOME/.profile.d/*; do source $file; done

# echo "export PORT=8888" | sudo tee /app/.profile.d/tsuru.sh
# create a new procfile that uses /start
# LC_ALL=C  perl -lne '/^(.*?):/ && print "$1: /start $1"' /app/Procfile  |sudo tee /Procfile
