#!/bin/bash -l

source /var/lib/tsuru/config
export HOME=/app

for file in $HOME/.profile.d/*; do source $file; done

hash -r
sudo -E /usr/local/bin/circusd /etc/circus/circus.ini --daemon --log-output /var/log/circus.log

